### PR TITLE
Enable sysadmin dashboard

### PR DESCRIPTION
**Pull request by clemente**

### CODE REVIEW

**Comment by cgopalan** [comment]
@clemente seems like there are build failures here.

**Comment by pomegranited** [comment]
@clemente CC @cgopalan  I just merged a commit that fixes the timeout issues you're seeing with CircleCI.

Could you please rebase this PR on the latest master and try again?

**Comment by clemente** [comment]
@cgopalan @pomegranited I rebased and pushed to trigger the rebuild. The build failures were due to Python3 code in node_modules, I think this was fixed, so this time it should build correctly.

**Comment by cgopalan** [comment]
@clemente how do I test this before merging to see if a new instance spawned has the new variable set? @haikuginger I remember you did this for me on https://github.com/open-craft/opencraft/pull/228 Is this something I would have access to? Or does it have to be tested by a core member?

**Comment by clemente** [comment]
@cgopalan I don't really know the fast way; probably it can be done from a local installation of OCIM.

However… are we suspicious that this variable won't be set in some cases? If all the other variables are being set correctly and all variables are treated equally (this is my supposition), can't we be certain that the deployed instance will have the variable?

**Comment by haikuginger** [comment]
@cgopalan, if you have a local copy of Ocim running in a Vagrant box (there are instructions in this repo), you can create a new instance and spawn an appserver, then terminate the process just so you can look at the variables it creates.

**Comment by cgopalan** [comment]
@clemente I am not sure if the variable will be set or not. I would assume that it would. Since a similar change from me was actually tested before merge by @haikuginger, I was wondering if I could do the same.
@haikuginger if you have a test instance running (or anybody else who has), can you test this? I am not sure that I have the bandwidth right now to start setting up a local instance and fiddling with it. However, if you think this is not necessary, I am good with that too.

**Comment by haikuginger** [comment]
Okay, this is not a formal review, but I can confirm that the variable was added to the `EDXAPP_FEATURES` var as expected.

**Comment by cgopalan** [comment]
@haikuginger thanks!

**Pull request merged**
