### PR TITLE
[BB-1030] collect coverage from test.browser and test.integration

### PR DESCRIPTION
**Pull request by dupainaulevain**
Fixes: https://github.com/open-craft/opencraft/issues/397

### CODE REVIEW

**Comment by antoviaque** [comment]
@dupainaulevain Why was this closed? Is it already addressed somewhere else?

**Comment by dupainaulevain** [comment]
It's closed because I won't complete it. It still is linked in the bb-1030 for someone to get inspiration from.

**Comment by antoviaque** [comment]
@dupainaulevain OK - what is missing from it? Is it just a review, or was this still WIP?

**Comment by dupainaulevain** [comment]
It's a WIP. I initially misunderstood how CircleCI handles parallel runs and produced an implementation that is not a good fit (first 4 commits). I then devised another implementation (last commit) which is suitable for both local and CircleCI coverage collection. However [it fails](https://circleci.com/gh/open-craft/opencraft/5206?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) because I don't know about CircleCI method to share artifacts between runs.

For someone familiar with CircleCI (which I'm not) and with admin access (which I don't have), it should be relatively easy to debug (ability to re-run a particular step) and get right. The recent CircleCI troubles preventing runs to see completion (Jessie troubles, or transient network access issues) suggested it would have been difficult for me to see this through.

**Comment by antoviaque** [comment]
@dupainaulevain Thanks for the details - FYI @xirdneh who is going to take over this work. CC @viadanna as reviewer.

**Pull request closed without merging**
