### PR TITLE
Security update - Django 1.10.7

### PR DESCRIPTION
**Pull request by antoviaque**
Cf https://github.com/open-craft/opencraft/blob/master/requirements.txt#L18

@bradenmacdonald FYI since you are the backup reviewer this week, want to have a look? Note that I haven't tested this, only bumped the version number to get the PR started.

FYI Django 1.11 has also just been released, so we will also need to create a task to upgrade it. https://docs.djangoproject.com/en/1.11/releases/1.11/

### CODE REVIEW

**Comment by bradenmacdonald** [comment]
@antoviaque  BTW normally the sprint firefighter would review this - the backup review is only for PRs that the sprint firefighter makes ;)

**Comment by antoviaque** [comment]
@bradenmacdonald Right, sorry -- I had in mind that the sprint firefighter would take care of this PR, so I pinged you for the review, but I didn't explicitly ask @bdero to take over this. 

@bdero Would you mind handling the rebase & deployment of this PR? You can just log the time on OC-1494 btw.

**Comment by bdero** [comment]
@antoviaque @bradenmacdonald Alrighty, I rebased this and deployed it to OCIM stage. After tests pass again I will merge this and deploy it to production.

**Comment by bdero** [comment]
This is running in production now.

**Comment by antoviaque** [comment]
@bdero Thank you!

**Pull request merged**
