### PR TITLE
Check that the heartbeat is functioning before activating

### PR DESCRIPTION
**Pull request by rocioar**

### CODE REVIEW

**Comment by rocioar** [comment]
@UmanShahzad  could you review this PR? I updated the way we check for heartbeat_active, and added tests. This should avoid the issue of it being on Ready state before it being actually active.

**Comment by rocioar** [comment]
@UmanShahzad big face palm here, I'm updating the code

**Comment by UmanShahzad** [comment]
@rocioar No worries, it happens :) I'm updating stage and re-spawning an appserver with this, hopefully it does it.

**Comment by rocioar** [comment]
@UmanShahzad  I still need to mock heartbeat_active on tests, will do this after dinner.

**Pull request merged**
