### PR TITLE
Make prospector play well with pylint again

### PR DESCRIPTION
**Pull request by mtyaka**
**Description**

Current version of prospector does not work with pylint 1.6.* (pylint warnings are silently suppressed).

This PR reverts pylint to 1.5.6 and fixes pylint violations that have accumulated while pylint wasn't working.

It also globally disables the `no-member` check, which is very unreliable and therefore not helpful.

For more info see https://tasks.opencraft.com/browse/OC-2143

**Testing Instructions**

1. Checkout this branch, update dependencies (`pip install -r requirements.txt`).
2. Run `make test_prospector`. It should report no violations.
3. Intentionally make some pylint violations (add an unused import somewhere, remove an existing `# pylint: disable=xxx` comment, etc...)
4. Run `make test_prospector` again, just to ensure that it correctly reports the violations you just made.

**Reviewer**:
- [ ] @e-kolpakov

### CODE REVIEW

**Comment by e-kolpakov** [comment]
@mtyaka :+1: except one minor thing - running `make test_prospector` on fresh checkout gives me 

```
instance/tests/models/test_openedx_database_mixins.py
  Line: 310
    pylint: syntax-error / invalid syntax
```

Probably because of the comma at the end.

Otherwise :+1:

- [x] I tested this: exactly as specified itesting instructions
- [x] I read through the code
- [x] ~~Includes documentation~~ Tech debt fix - no docs required.

**Comment by mtyaka** [comment]
Rebased from 929cbb6e162981b8739cff9ad06bc32ed5e8a81b.

**Comment by mtyaka** [comment]
Thanks @e-kolpakov! I'm not sure why you were seeing that warning/error - it does not show up for me and it doesn't show up on circleci either. Maybe you're running a slightly different version of pylint? In your virtualenv, `pip show pylint` should report version `1.5.6` and `pip show prospector` should report `0.12.4`.

There were further changes on master, so I had to rebase again and fix/silence a couple more warnings.

**Comment by mtyaka** [comment]
Rebased from 1517d94e2f45f2bc79e9583410e3ad9f6033329d

**Pull request merged**
