### PR TITLE
fix: Skip empty hashes when cleaning up OpenStack servers created by CI

### PR DESCRIPTION
**Pull request by kewne**
Related tickets:
* [BB-4378 (OpenCraft Internal)](https://tasks.opencraft.com/browse/BB-4378)

# Testing

I've already pushed this to the `ci-cleanup` branch, see [CI results](https://app.circleci.com/pipelines/github/open-craft/opencraft/4121/workflows/35c5152b-f885-4916-9fad-5edb896df98c/jobs/37066)

### CODE REVIEW

**Comment by lgp171188** [comment]
@kewne, please fix the failing code quality tests.

**Comment by kewne** [comment]
@lgp171188 Sorry for the delay; the tests are now passing.

**Comment by lgp171188** [comment]
@kewne, 
> Skip empty hashes when cleaning up OP servers

what do you mean by `OP servers` here?

**Comment by kewne** [comment]
@lgp171188 Sorry, missed the ping... it's a typo, it should be OS (OpenStack)...

**Comment by kewne** [comment]
@lgp171188 I've amended the commit and PR title and checks are passing, can you take a look if necessary and approve?

**Review by lgp171188 — APPROVED** [review]
:+1: 
- [x] I verified from the passing CI cleanup job that this works as expected and resolves the issue  due to which the job tried to delete an invalid DNS record in Gandi and failed.
- [x] I read through the code
- [x] ~~I checked for accessibility issues~~ NA
- [x] ~~Includes documentation~~ NA

**Pull request merged**
