### PR TITLE
[SE-3953] Updates NewRelic policy to check for failure instead

### PR DESCRIPTION
**Pull request by nizarmah**
This check checks for failure instead of success.

This check also makes sure that ~3~ 2 consecutive failures happened before creating an alert/violation.

Once ~3~ 2 alerts happen in the matter of ~16~ 11 minutes, a violation will be opened. In order to guarantee the alert is closed, we use the 'loss of signal' or 'signal expiration'. If we don't have any signal for a duration of ~16~ 11 mins, ie no failed request for ~16~ 11 mins, it means that all issues were resolved, so close the violation.

**JIRA tickets**: SE-3953

**Screenshots**: 

* Opening Alert:
image

* Closing Alert:
image

**Sandbox Instance**: [Sandbox Instance](https://manage.opencraft.com/instance/22310/)

**Testing instructions**:

1. Open [NewRelic Synthetic Summary](https://one.newrelic.com/launcher/nr1-core.explorer?pane=eyJuZXJkbGV0SWQiOiJzeW50aGV0aWNzLW5lcmRsZXRzLm1vbml0b3Itb3ZlcnZpZXciLCJpc092ZXJ2aWV3Ijp0cnVlLCJyZWZlcnJlcnMiOnsibGF1bmNoZXJJZCI6InN5bnRoZXRpY3MtbmVyZGxldHMuaG9tZSIsIm5lcmRsZXRJZCI6InN5bnRoZXRpY3MtbmVyZGxldHMubW9uaXRvci1saXN0In0sImVudGl0eUlkIjoiTVRNME5qazFOWHhUV1U1VVNIeE5UMDVKVkU5U2ZHWXdORGs1Wm1KaExXSTVPR1F0TkRGa05pMWlaakUxTFRjeFlUWTFZV0V5Wm1Ga1lRIn0=&sidebars[0]=eyJuZXJkbGV0SWQiOiJucjEtY29yZS5hY3Rpb25zIiwiZW50aXR5SWQiOiJNVE0wTmprMU5YeFRXVTVVU0h4TlQwNUpWRTlTZkdZd05EazVabUpoTFdJNU9HUXROREZrTmkxaVpqRTFMVGN4WVRZMVlXRXlabUZrWVEiLCJzZWxlY3RlZE5lcmRsZXQiOnsibmVyZGxldElkIjoic3ludGhldGljcy1uZXJkbGV0cy5tb25pdG9yLW92ZXJ2aWV3IiwiaXNPdmVydmlldyI6dHJ1ZX19&platform[accountId]=1346955&platform[filters]=IihuYW1lIGxpa2UgJ3ByMjU2OTUuc2FuZGJveC5vcGVuY3JhZnQuaG9zdGluZycgb3IgaWQgPSAncHIyNTY5NS5zYW5kYm94Lm9wZW5jcmFmdC5ob3N0aW5nJyBvciBkb21haW5JZCA9ICdwcjI1Njk1LnNhbmRib3gub3BlbmNyYWZ0Lmhvc3RpbmcnKSI=&platform[timeRange][duration]=1800000&platform[$isFallbackTimeRange]=true) for the sandbox instance's extended heartbeat check in a new tab.
2. Open [NewRelic Policy](https://one.newrelic.com/launcher/nrai.launcher?pane=eyJuZXJkbGV0SWQiOiJhbGVydGluZy11aS1jbGFzc2ljLnBvbGljaWVzIiwibmF2IjoiUG9saWNpZXMiLCJwb2xpY3lJZCI6MTE1MDk2N30=&sidebars[0]=eyJuZXJkbGV0SWQiOiJucmFpLm5hdmlnYXRpb24tYmFyIiwibmF2IjoiUG9saWNpZXMifQ==&platform[accountId]=1346955) for the sandbox instance's extended heartbeat check in a new tab.
3. SSH into the sandbox instance.
`ssh 149.202.172.84`
4. Set the LMS env settings yaml file to the error file.
`sudo cp /edx/etc/lms-error.yml /edx/etc/lms.yml`
5. Restart the LMS
`/edx/bin/supervisorctl restart lms`
6. Wait ~16~ 11 mins, and an incident should be opened for the sandbox instance.
7. SSH into the sandbox instance, again.
`ssh 149.202.172.84`
8. Set the LMS env settings yaml file to the fix file.
`sudo cp /edx/etc/lms-fix.yml /edx/etc/lms.yml`
9. Restart the LMS, again.
`/edx/bin/supervisorctl restart lms`
10. Wait ~16~ 11 mins, and the incident should be closed for the sandbox instance.

**Author notes and concerns**:

1. NewRelic solution architect explains how to automatically close Failure checking alerts in this [forum thread](https://discuss.newrelic.com/t/synthetic-check-nrql-alerts-not-getting-closed/121690).
 
**Reviewers**
- [x] @arbrandes 
- [ ] @mtyaka 
- [ ] @gabor-boros

### CODE REVIEW

**Review by arbrandes — APPROVED** [review]
@nizarmah, :+1:

- [x] I tested this as instructed.  There were no actual notifications sent out because I presume they were disabled for the sandbox in question, but the thresholds were met as defined.
- [x] I read through the code
- [ ] ~~I checked for accessibility issues~~
- [x] Includes documentation in the form of unit tests

**Comment by nizarmah** [comment]
@arbrandes actually, there were some alerts 😛 They were sent to ops though and my email, since those were the specified notification channels. Sorry I should've mentioned that in the testing instructions.

Here are the alerts I received from your testing:
* Opening alert:
image

* Closing alert:
image

**Comment by nizarmah** [comment]
@mtyaka 

https://github.com/open-craft/opencraft/blob/329fcf1b5f5e8ff33f5b6949f2c16f334b80bcd4/instance/tests/test_newrelic.py#L269-L272

I wanted to ask if the `since_value` has an effect or if it should be removed? 
When adding it manually to a NewRelic query, here's what I got:

image

I'm not really sure if it has any effect on what is going on, since mainly the threshold for the condition is the most valuable. 
I went over their docs, but they don't seem to be that informative.

Let me know please 👍🏼

**Comment by nizarmah** [comment]
After changing the alert condition to respond after 2 consecutive alerts instead of 3, I tested the values in New Relic manually.

* Opening Alert
image

* Closing Alert
image

* Graph
image

**Pull request merged**
