### PR TITLE
[SE-2729] Revert PRs #592 and #603

### PR DESCRIPTION
**Pull request by fferrin**
This PR reverts PRs #592 and #603

**JIRA ticket**: [SE-2729](https://tasks.opencraft.com/browse/SE-2729)

**Reviewers**
- [x] @swalladge

### CODE REVIEW

**Comment by fferrin** [comment]
@symbolist maybe I'll need your help here to approve this MR, given that Xavier wanted this for today and Samuel won't be here for the next hours. Can you approve this?

**Comment by swalladge** [comment]
@fferrin the migrations are broken for me - I think you'll need to keep the same migrations as is currently on master, and add the one to remove the notes field on top. Editing the names of the existing migration files breaks django's migration tracking state.

**Comment by fferrin** [comment]
@swalladge I'm getting the same errors as in a previous [PR](https://github.com/open-craft/opencraft/pull/608) of mine, but now master isn't failling. Have you seen this error before?

**Comment by swalladge** [comment]
@fferrin ah it could be because the tests there are relying on environment variables that aren't shared to branches in third party forks?

**Comment by swalladge** [comment]
@fferrin :+1: Please deploy on stage (and run migrations) before merging to master.

- [x] I tested this: checked that it reverts the correct commits; checked the migrations for consistency
- [x] I read through the code
- [ ] NA I checked for accessibility issues
- [ ] NA Includes documentation

**Comment by antoviaque** [comment]
@fferrin @swalladge Thanks for getting this done!

**Pull request merged**
