### PR TITLE
BB-4198: Batch dependabot upgrades + package upgrades

### PR DESCRIPTION
**Pull request by giovannicimolin**
Upgrades all packages with vulnerability warnings.
:warning:  **Waiting for CI checks!** :warning: 

This unpins a lot of dependencies from OpenStack to make upgrades easier.

**Reviewers:**
- [x] Any FF (CC @s0b0lev @gabor-boros @nizarmah @pomegranited @xitij2000)

### CODE REVIEW

**Comment by giovannicimolin** [comment]
Ugh, e2e tests started failing. I'll check them before my EOD today.

**Comment by giovannicimolin** [comment]
Finally found the issue: `pyjwt` doesn't work well with the `drf-simplejwt` library (at least in Python 3.6 and using the latest supported version).

I've pinned the package to solve the issue.
```
# Pinned version since this causes issues with DRF-JWT package when using older python versions (3.8 and below)
pyjwt==1.7.1
```

**Comment by gabor-boros** [comment]
👍  🎉 🚀 

- ~[] I tested what's in the test instructions~
- [x] I read through the code
- ~[ ] I checked for accessibility issues~
- ~[ ] Includes documentation~
- ~[ ] I made sure any change in configuration variables is reflected in the corresponding client's `configuration-secure` repository.~

**Review by gabor-boros — APPROVED** [review]

**Comment by giovannicimolin** [comment]
It looks like I broke something during the rebase :sob: 
I'll investigate tomorrow.

**Comment by giovannicimolin** [comment]
Dropped the openstack package upgrades since they are cause too many issues and I'm out of FF time.

**Comment by janimo** [comment]
@giovannicimolin CI passed after a manual retry.

**Pull request merged**
