### PR TITLE
Revert "Pin setuptools to 32 as a bug workaround."

### PR DESCRIPTION
**Pull request by bdero**
This reverts commit 694c7cc15bd6fd943bbd4b10ea854141ffbd5b65.

This should be merged when the source issue discussed in https://github.com/open-craft/opencraft/pull/205 is resolved.

### CODE REVIEW

**Comment by bdero** [comment]
I tested this locally by running `vagrant up` on a fresh environment. CC @antoviaque 

@haikuginger Would you be able to give this a sprint firefighter review?

**Comment by haikuginger** [comment]
@bdero, sure. :)

**Comment by haikuginger** [comment]
Working on testing this now. Ran into some issues at first, but only because VirtualBox had been updated since the last time Vagrant was, so Vagrant was still pointed to the old location for the Guest Additions ISO.

**Comment by haikuginger** [comment]
:+1:

- [x] I tested this: I cloned this repo in an empty environment and ran `vagrant up` successfully without any setuptools issues.
- [x] I read through the code
- [x] ~~I checked for accessibility issues~~
- [x] ~~Includes documentation~~

**Comment by haikuginger** [comment]
@bdero, what's the relevant OpenCraft story?

**Comment by bdero** [comment]
@haikuginger Thanks! This temporary fix was to help unblock this about a month ago: https://tasks.opencraft.com/browse/OC-2479

**Pull request merged**
