### PR TITLE
Fix playbooks repo typo in README.md

### PR DESCRIPTION
**Pull request by ahmedaljazzar**
This is to fix a typo in README.md file which leads to a 404 page when trying to access the [playbooks](https://github.com/open-craft/ansible-playbooks) repo.

### CODE REVIEW

**Comment by clemente** [comment]
@ahmedaljazzar This is approved and it's a minor change, so you can already merge it (after rebasing).

**Comment by ahmedaljazzar** [comment]
@UmanShahzad, @clemente I don't know exactly why the tests are failing. I tried triggering the build again but I need to have a permission for that. Can you check it for me please?

**Comment by ahmedaljazzar** [comment]
Just noticed that I'm not logged in, fail. Actually the tests are failing on all recent PRs  (#338, #327 and this one) in the same module.

```
======================================================================
ERROR: test_ansible_failignore (instance.tests.integration.integration_instance.InstanceIntegrationTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/circleci/project/instance/tests/decorators.py", line 46, in _wrap
    *args, **kwargs)
  File "/usr/local/lib/python3.5/unittest/mock.py", line 1159, in patched
    return func(*args, **keywargs)
  File "/home/circleci/project/venv/lib/python3.5/site-packages/django/test/utils.py", line 205, in inner
    return func(*args, **kwargs)
  File "/home/circleci/project/instance/tests/integration/integration_instance.py", line 447, in test_ansible_failignore
    spawn_appserver(instance.ref.pk, mark_active_on_success=True, num_attempts=1)
  File "/home/circleci/project/venv/lib/python3.5/site-packages/huey/api.py", line 116, in inner_run
    return self.enqueue(cmd)
  File "/home/circleci/project/venv/lib/python3.5/site-packages/huey/api.py", line 215, in enqueue
    return task.execute()
  File "/home/circleci/project/venv/lib/python3.5/site-packages/huey/api.py", line 560, in execute
    return func(*args, **kwargs)
  File "/home/circleci/project/venv/lib/python3.5/site-packages/huey/contrib/djhuey/__init__.py", line 91, in inner
    return fn(*args, **kwargs)
  File "/home/circleci/project/instance/tasks.py", line 70, in spawn_appserver
    failure_tag=failure_tag
  File "/home/circleci/project/instance/logging.py", line 51, in wrapper
    return method(self, *args, **kwds)
  File "/home/circleci/project/instance/models/openedx_instance.py", line 252, in spawn_appserver
    app_server = self._spawn_appserver()
  File "/home/circleci/project/instance/models/openedx_instance.py", line 207, in _spawn_appserver
    self.reconfigure_load_balancer()
  File "/home/circleci/project/instance/models/mixins/load_balanced.py", line 79, in reconfigure_load_balancer
    load_balancing_server.reconfigure(self.ref.pk)
  File "/home/circleci/project/instance/models/load_balancer.py", line 265, in reconfigure
    self.run_playbook(self.get_ansible_vars(triggering_instance_id))
  File "/home/circleci/project/instance/models/load_balancer.py", line 235, in run_playbook
    raise ReconfigurationFailed
instance.models.load_balancer.ReconfigurationFailed

----------------------------------------------------------------------
```

I rebased the PR, and pushed it again.

**Comment by UmanShahzad** [comment]
Rebuildin for ya..

**Comment by clemente** [comment]
@ahmedaljazzar We've had flaky tests in CircleCI lately, I have seen that `ReconfigurationFailed` error many times. Normally we try again many times until it works, but there should be better ways. I think @viadanna found some way to avoid it (like moving tests SWIFT→S3), we should discuss that.
Anyway this PR isn't urgent. For urgent ones, you could actually run tests in your computer (but it's not worth it with „integration tests“, it requires too much config and takes too long).

**Pull request merged**
