### PR TITLE
Change simple theme version back to master

### PR DESCRIPTION
**Pull request by 0x29a**
No testing required. If CI checks passed — everything works as expected.

### CODE REVIEW

**Comment by 0x29a** [comment]
@farhaanbukhsh, would you be able to review this once CI pipeline pass? This was a temporary fix to enable Koa builds, but now it's redundant, since mentioned branch was merged in simple theme.

**Comment by farhaanbukhsh** [comment]
@0x29a sure :)

**Comment by 0x29a** [comment]
@farhaanbukhsh, all checks have passed.

**Comment by farhaanbukhsh** [comment]
Will have a look in sometime 😊

**Review by farhaanbukhsh — APPROVED** [review]
👍 

- [x] I tested this: CI is passing 
- [x] I read through the code
- [ ] ~~I checked for accessibility issues~~
- [ ] ~~Includes documentation~~
- [ ] ~~I made sure any change in configuration variables is reflected in the corresponding client's `configuration-secure` repository.~~

**Pull request merged**
