### PR TITLE
Watch for PRs for the Sandbox team, instead of Owners.

### PR DESCRIPTION
**Pull request by UmanShahzad**
Previously, PRs were only being watched for by members of the `Owners` team. As part of improving on-boarding, this PR takes advantage of @antoviaque's addition of the "Sandbox" team, by watching for PRs against `edx/edx-platform` by members of that group instead. This is to make it so that candidates can also automatically have sandboxes provisioned for them, but also to make it easier for us to off-board.

### CODE REVIEW

**Comment by bradenmacdonald** [comment]
Thanks @UmanShahzad ! The code looks good to me - I'll test it tomorrow, unless someone else tests it first. We only need one person to do the manual testing (make sure the migration applies fine, etc.)

**Comment by antoviaque** [comment]
@UmanShahzad Thanks! To remember to add new developers to that group (and remove them), can you add this group to the on/off-boarding steps from https://github.com/open-craft/documentation/blob/master/onboarding_steps_manager.md ? Steps 7 and 3 respectively.

**Comment by UmanShahzad** [comment]
@antoviaque Ah, good catch: https://github.com/open-craft/documentation/pull/156/commits/5cc64e563df0f63433f70e0a7b567cfce73f06e5

**Comment by UmanShahzad** [comment]
@bradenmacdonald Can I merge?

**Comment by bradenmacdonald** [comment]
@UmanShahzad  Yep!

**Pull request merged**
