### PR TITLE
Fix shell instructions

### PR DESCRIPTION
**Pull request by omarkhan**
You have to use `OpenEdxInstance.objects.create`, you can't instatiate the instance first and save it later.

### CODE REVIEW

**Comment by omarkhan** [comment]
@pomegranited this is just a quick follow up to https://github.com/open-craft/opencraft/pull/41. Does it look ok?

**Comment by pomegranited** [comment]
@omarkhan Looks good, just one question: When re-provisioning or deleting, how do you get the ``instance`` instance?

**Comment by omarkhan** [comment]
@pomegranited you can use django's usual queryset methods, like this:

```python
instance = OpenEdXInstance.objects.get(name__contains='...')
```

or

```python
instance = OpenEdXInstance.objects.get(github_pr_url='...')
```

I will add this to the README

**Comment by pomegranited** [comment]
Thank you, @omarkhan ! :+1:

**Pull request merged**
