### PR TITLE
Fix broken link to OpenStack docs.

### PR DESCRIPTION
**Pull request by UmanShahzad**
Super tiny change, noticed it as reading through `README.md`.

### CODE REVIEW

**Comment by bradenmacdonald** [comment]
Thanks @UmanShahzad ! This looks great, but we are waiting to resolve some issues with our CI build before we can merge.

**Comment by UmanShahzad** [comment]
No worries @bradenmacdonald ; this is hardly urgent :)

**Comment by UmanShahzad** [comment]
@bradenmacdonald We had @BogdanL mention this link was broken in his on-boarding. Can we look at getting it merged as part of on-boarding improvement? (Unless we're deciding to scratch the Ocim setup step).

**Comment by bradenmacdonald** [comment]
@UmanShahzad  Can you rebase this, or merge master into this branch, to trigger a new build and remove the "out-of-date with the base branch" restriction? Then we should get a green build and be able to merge.

**Comment by UmanShahzad** [comment]
@bradenmacdonald Done. When it turns green I'll merge.

**Comment by bradenmacdonald** [comment]
@UmanShahzad  Actually, guess what? They changed the link again... [Ugh](https://www.w3.org/Provider/Style/URI).

**Comment by UmanShahzad** [comment]
@bradenmacdonald We can use https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux_OpenStack_Platform/5/html/End_User_Guide/cli_openrc.html to be possibly more reliable. I think that's the same content as it matches https://web.archive.org/web/20161105104308/https://docs.openstack.org/user-guide/common/cli-set-environment-variables-using-openstack-rc.html (ok, not fully, but almost the same). Or just link to the web archive :)

**Comment by bradenmacdonald** [comment]
@UmanShahzad  Either one is fine, but I'd suggest the archive.org one as it will be more stable.

**Pull request merged**
