### PR TITLE
SE-1541 Disable broker heartbeat for celery workers

### PR DESCRIPTION
**Pull request by swalladge**
Celery workers are dodgy and don't appear to be actually sending
heartbeats even when configured (as by default) to a non-zero heartbeat
interval. This instructs them to disable amqp protocol heartbeats
altogether. This, combined with setting heartbeat to 0 on the rabbitmq
server, disables amqp protocol heartbeat checks, and we should avoid
getting any connection reset issues.

This works in conjunction with https://github.com/open-craft/ansible-playbooks/pull/148 and https://github.com/edx/edx-platform/pull/21567 . However, it can be tested without those PRs (we just check that it correctly passes through the variable).

**Test instructions**:

- deploy ocim with this branch
- create a master instance with the default config
- launch an appserver on the instance
- ssh into the appserver and view /edx/etc/lms.yml and /edx/etc/studio.yml and verify that the line `BROKER_HEARTBEAT: 0` is present in both.

**Reviewer**:

- [x] @gr4yscale

### CODE REVIEW

**Comment by gr4yscale** [comment]
:+1: Nice work tracking all of this down, @swalladge 

- [x] I tested this: SSH'd from ocim stage into the VM for [the appserver you provisioned from this branch](https://stage.console.opencraft.com/instance/4470/edx-appserver/1726/) and checked for the presence of `BROKER_HEARTBEAT: 0` in `lms.yml` and `studio.yml`:

```
(opencraft) www-data@stage:/home/ubuntu$ ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o CheckHostIP=no ubuntu@vm1.se-1541-test-provision.stage.opencraft.hosting

ubuntu@edxapp-se-1541-test--appserver-3:/edx/etc$ sudo cat lms.yml | grep BROKER
BROKER_HEARTBEAT: 0
ubuntu@edxapp-se-1541-test--appserver-3:/edx/etc$ sudo cat studio.yml | grep BROKER
BROKER_HEARTBEAT: 0
```
 
- [x] I read through the code
- [ ] I checked for accessibility issues n/a
- [ ] Includes documentation n/a
- [ ] I made sure any change in configuration variables is reflected in the corresponding
    client's `configuration-secure` repository. n/a

**Comment by swalladge** [comment]
Thanks @gr4yscale :) Would you mind giving the github review approval to enable merging?

**Comment by gr4yscale** [comment]
@swalladge Done, still stuck in the GitLab state of mind, aha

**Comment by swalladge** [comment]
@gr4yscale Thanks, no problem at all! (I think I also forgot to request a review, so not your fault) :smile:

**Comment by swalladge** [comment]
@brett-oc this is ready to merge once you've given it an approving review. :)

**Comment by pomegranited** [comment]
@swalladge  This PR looks exactly the same as when @gr4yscale reviewed it, so do you actually need another approval?

**Comment by swalladge** [comment]
@pomegranited Yes because 

> At least 1 approving review is required by reviewers with write access.

**Pull request merged**
